# Generated by Django 4.2.11 on 2026-03-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('condicion_pelo', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_piel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primerapel', models.CharField(db_column='primerApel', max_length=50)),
                ('segapel', models.CharField(blank=True, db_column='segApel', max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primerapel', models.CharField(db_column='primerApel', max_length=50)),
                ('segapel', models.CharField(blank=True, db_column='segApel', max_length=50, null=True)),
                ('fechacontra', models.DateField(db_column='fechaContra')),
                ('usuario', models.CharField(max_length=30, unique=True)),
                ('claveacceso', models.CharField(db_column='claveAcceso', max_length=255)),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estado_cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estado_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoMascota',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estado_mascota',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tamaño',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelefonoEmpleado',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_column='Telefono', max_length=15)),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'telefono_empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelefonoCliente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_column='Telefono', max_length=15)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
            ],
            options={
                'db_table': 'telefono_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tamano', models.ForeignKey(db_column='tamaño', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tamano')),
            ],
            options={
                'db_table': 'raza',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(db_column='area', on_delete=django.db.models.deletion.DO_NOTHING, to='core.area')),
            ],
            options={
                'db_table': 'puesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(db_column='fecha_Pago')),
                ('monto_total', models.DecimalField(db_column='Monto_total', decimal_places=2, max_digits=10)),
                ('cita', models.OneToOneField(db_column='cita', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cita')),
                ('tipo_pago', models.ForeignKey(db_column='tipo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipopago')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechanac', models.DateField(blank=True, db_column='fechaNac', null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('estado_mascota', models.ForeignKey(db_column='estado_mascota', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadomascota')),
                ('raza', models.ForeignKey(db_column='raza', on_delete=django.db.models.deletion.DO_NOTHING, to='core.raza')),
            ],
            options={
                'db_table': 'mascota',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(db_column='puesto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.puesto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadocliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.ForeignKey(db_column='estado_cita', on_delete=django.db.models.deletion.DO_NOTHING, to='core.estadocita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(db_column='mascota', on_delete=django.db.models.deletion.DO_NOTHING, to='core.mascota'),
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('servicio', models.OneToOneField(db_column='servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.servicio')),
                ('precioaplicado', models.DecimalField(db_column='precioAplicado', decimal_places=2, max_digits=8)),
                ('cita', models.ForeignKey(db_column='cita', on_delete=django.db.models.deletion.DO_NOTHING, to='core.cita')),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
            options={
                'db_table': 'detalle_cita',
                'managed': True,
                'unique_together': {('servicio', 'cita')},
            },
        ),
    ]
