# Generated by Django 4.2.11 on 2026-03-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'verbose_name': 'Estilista', 'verbose_name_plural': 'Estilistas'},
        ),
    ]
