# Generated by Django 4.2.11 on 2026-03-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='empleado',
            field=models.ForeignKey(blank=True, db_column='empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado'),
        ),
    ]
